### ISSUE TITLE
Cannot use angular-sails. Just got `legacy_get` error message

### ISSUE THREAD

**Issue by pewh** [janpantel/angular-sails#30]
I got these error messages on socket.io-client latest version (1.0.6) & sails 0.10-rc8

```
TypeError: Property 'legacy_get' of object #<Socket> is not a function
    at Socket.socket.(anonymous function) [as get] (http://localhost:3000/angular-sails/dist/angular-sails.js:55:51)
    at http://localhost:3000/product/product-controller.js:23:14
    at new <anonymous> (http://localhost:3000/product/product-controller.js:36:6)
    at invoke (http://localhost:3000/angular/angular.js:3917:17)
    at Object.instantiate (http://localhost:3000/angular/angular.js:3928:23)
    at http://localhost:3000/angular/angular.js:7216:28
    at http://localhost:3000/angular-ui-router/release/angular-ui-router.js:2797:28
    at nodeLinkFn (http://localhost:3000/angular/angular.js:6648:13)
    at compositeLinkFn (http://localhost:3000/angular/angular.js:6039:13)
    at publicLinkFn (http://localhost:3000/angular/angular.js:5934:30) <div class="col-sm-11 ng-scope" ui-view=""> angular.js:9959
XMLHttpRequest cannot load http://127.0.0.1:1337/socket.io/?EIO=2&transport=polling&t=1404913877808-0. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. (index):1
XMLHttpRequest cannot load http://127.0.0.1:1337/socket.io/?EIO=2&transport=polling&t=1404913879111-1. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. 
XMLHttpRequest cannot load http://127.0.0.1:1337/socket.io/?EIO=2&transport=polling&t=1404913877808-2. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. (index):1
XMLHttpRequest cannot load http://127.0.0.1:1337/socket.io/?EIO=2&transport=polling&t=1404913879111-3. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. 
...loop on same message error...
```

if I use socket.io-client version 0.9.16, I only get 1 error message

```
TypeError: Property 'legacy_get' of object #<SocketNamespace> is not a function
    at SocketNamespace.socket.(anonymous function) [as get] (http://localhost:3000/angular-sails/dist/angular-sails.js:55:51)
    at http://localhost:3000/product/product-controller.js:23:14
    at new <anonymous> (http://localhost:3000/product/product-controller.js:36:6)
    at invoke (http://localhost:3000/angular/angular.js:3917:17)
    at Object.instantiate (http://localhost:3000/angular/angular.js:3928:23)
    at http://localhost:3000/angular/angular.js:7216:28
    at http://localhost:3000/angular-ui-router/release/angular-ui-router.js:2797:28
    at nodeLinkFn (http://localhost:3000/angular/angular.js:6648:13)
    at compositeLinkFn (http://localhost:3000/angular/angular.js:6039:13)
    at publicLinkFn (http://localhost:3000/angular/angular.js:5934:30) <div class="col-sm-11 ng-scope" ui-view=""> 
```

Here is my controller:

```
angular.module('anystore.product').controller('ProductCtrl', [
    '$scope',
    '$log',
    '$sails',
  function ($scope, $log, $sails) {
    'use strict';

    $scope.products = [];

    (function() {
      $sails.on('connection', function (result) {
        console.log(result);
      });
      
      $sails.get('/asas')
        .success(function (data) {
          $scope.products = data;
        })
        .error(function (data) {
          $log('error: ' + data);
        });

      $sails.on('message', function (message) {
        if (message.verb === 'create') {
          $scope.products.push(message.data);
        }
      });
    }());
  }
]);
```

**Comment by TheSharpieOne** [comment]
This may be a compatibility issue with sails.io.js and sailsjs.  What version of sailsjs are you using and what version of sails.io.js are you using?
Its also worth noting that the [distributed version of sails.io.js](https://github.com/balderdashy/sails.io.js/blob/master/dist/sails.io.js) comes with [socket.io-client](https://github.com/balderdashy/sails.io.js/blob/master/dist/sails.io.js#L1).

**Comment by TheSharpieOne** [comment]
Closing this issue as it is not active.  Try the latest release and if you are still experiencing this issue, please re-open it.
