### ISSUE TITLE
undefined is not a function when calling $sails.get('url')

### ISSUE THREAD

**Issue by prisonier** [janpantel/angular-sails#49]
Maybe because i run sails 0.11 ?
The very strange thing is i can see that get is a function when i console.log($sails).

```javascript
 

  |>    Now connected to Sails.
\___/   For help, see: http://bit.ly/1DmTvgK
        (using browser SDK @v0.11.0)


// When i console.log
Socket {io: Manager, nsp: "/", json: Socket, ids: 0, acks: Object…}
_callbacks: Object
acks: Object
connected: true
delete: function (e,o,i){var u=s();return void 0===i&&n.isFunction(o)&&(i=o,o=null),u.promise.then(i),c["legacy_"+t](e,o,function(n){l(u,n)}),u.promise}
disconnected: false
get: function (e,o,i){var u=s();return void 0===i&&n.isFunction(o)&&(i=o,o=null),u.promise.then(i),c["legacy_"+t](e,o,function(n){l(u,n)}),u.promise}
ids: 0

etc ....

// When i try to access url
TypeError: undefined is not a function
    at Socket.n.module.provider.$get.c.(anonymous function) [as get] (http://localhost:1337/js/other_dependencies/angular-sails.min.js:1:685)
    at new <anonymous> (http://localhost:1337/js/angular/controller/StarCtrl.js:7:10)
    at invoke (http://localhost:1337/js/base_dependencies/angular.js:4185:17)
    at Object.instantiate (http://localhost:1337/js/base_dependencies/angular.js:4193:27)
    at http://localhost:1337/js/base_dependencies/angular.js:8462:28
    at link (http://localhost:1337/js/other_dependencies/angular-route.min.js:7:270)
    at invokeLinkFn (http://localhost:1337/js/base_dependencies/angular.js:8219:9)
    at nodeLinkFn (http://localhost:1337/js/base_dependencies/angular.js:7729:11)
    at compositeLinkFn (http://localhost:1337/js/base_dependencies/angular.js:7078:13)
    at publicLinkFn (http://localhost:1337/js/base_dependencies/angular.js:6957:30) <div ng-hide="loading" ng-view="" class="ng-scope">
```

Finally the code involved : 

``` javascript
app.controller('StarCtrl', function ($scope, $routeParams, $sails) {

  $scope.loading = true

  console.log($sails)

  $sails.get('/star/profile/'+$routeParams.readable_id)
    .then(function(resp){
      console.log(resp.data)
    }, function(resp){
      alert('Houston, we got a problem!')
    });

```

**Comment by TheSharpieOne** [comment]
Can you use a non-minified version of angular-sails to give a better line number for the error.
Also, I am about to create a new release for all of the changes and updates we have been working on to have angular-sails better integrate with sail.io.js.  Maybe the new version will fix it.

**Comment by prisonier** [comment]
yes sir

``` javascript

 TypeError: undefined is not a function
    at Socket.angular.module.provider.$get.socket.(anonymous function) [as get] (http://localhost:1337/js/other_dependencies/angular-sails.js:55:51)
    at new <anonymous> (http://localhost:1337/js/angular/controller/StarCtrl.js:21:10)
    at Object.invoke (http://localhost:1337/js/base_dependencies/angular.js:4185:17)
    at $get.extend.instance (http://localhost:1337/js/base_dependencies/angular.js:8454:21)
    at http://localhost:1337/js/base_dependencies/angular.js:7700:13
    at forEach (http://localhost:1337/js/base_dependencies/angular.js:331:20)
    at nodeLinkFn (http://localhost:1337/js/base_dependencies/angular.js:7699:11)
    at compositeLinkFn (http://localhost:1337/js/base_dependencies/angular.js:7078:13)
    at publicLinkFn (http://localhost:1337/js/base_dependencies/angular.js:6957:30)
    at link (http://localhost:1337/js/other_dependencies/angular-route.min.js:7:410) <div ng-hide="loading" ng-view="" class="ng-scope">

```

**Comment by prisonier** [comment]
BTW when i'm using legacy sails.io.js methods it wroks exactly as expected : 

``` javascript
    getStarSocket : function(readable_id){
      var deferred = $q.defer()

      io.socket.get('/star/profile/'+readable_id, function(star, jwres){

        if(jwres.statusCode === 200){
          factory.star = star
          deferred.resolve(factory.star)
        }else{
          deferred.reject('error')
        }
      })

      return deferred.promise

    }
```

**Comment by TheSharpieOne** [comment]
You may want to update your angular-sails.  The current release has [nothing on that line](https://github.com/janpantel/angular-sails/blob/380e82c3ac396b7516e531028432eef171fc50e9/dist/angular-sails.js#L55).  Looks like you may have on [this version](https://github.com/janpantel/angular-sails/blob/0f54848c17d333cf3cdcd1d60aa9f8f4baf0fba9/dist/angular-sails.js#L55)

**Comment by TheSharpieOne** [comment]
Ok, just released a brand new version, the one I mentioned before.  Its tested (has tests with CI and is passing).  It also works better with newer versions of sails.io.js which come with newer versions of sailsjs.  Get that release and let me know.

**Comment by prisonier** [comment]
Ok i'll give a try today. But be advised that i've download ngSails with wower yesterday around 6pm GMT

**Comment by prisonier** [comment]
Still getting the same error at the same function, line 78 in the version : 

``` javascript
 TypeError: undefined is not a function
    at Socket.angular.module.provider.$get.socket.(anonymous function) [as get] (http://localhost:1337/js/other_dependencies/angular-sails.js:78:43)
    at Object.factory.getStarSocket (http://localhost:1337/js/angular/factory/StarFactory.js:30:14)
    at new <anonymous> (http://localhost:1337/js/angular/controller/StarCtrl.js:6:15)
    at Object.invoke (http://localhost:1337/js/base_dependencies/angular.js:4185:17)
    at $get.extend.instance (http://localhost:1337/js/base_dependencies/angular.js:8454:21)
    at http://localhost:1337/js/base_dependencies/angular.js:7700:13
    at forEach (http://localhost:1337/js/base_dependencies/angular.js:331:20)
    at nodeLinkFn (http://localhost:1337/js/base_dependencies/angular.js:7699:11)
    at compositeLinkFn (http://localhost:1337/js/base_dependencies/angular.js:7078:13)
    at publicLinkFn (http://localhost:1337/js/base_dependencies/angular.js:6957:30) <div ng-hide="loading" ng-view="" class="ng-scope">
```

**Comment by prisonier** [comment]
After 1 hour fighting against the world, it works. 

BUT : 
1. now i'm not able to use sails.io without ngSails -> console.log(io) returns undefined -> normal ?
2. it seems that there is no connection done with websocket until i call ngSails -> this is different from sails.io natural behavior -> normal ?

**Comment by TheSharpieOne** [comment]
1. is not normal.  `io` should be defined, it is [how ngSails connects](https://github.com/janpantel/angular-sails/blob/master/src/service/angular-sails.js#L80) and [manipulates sails.io settings](https://github.com/janpantel/angular-sails/blob/master/src/service/angular-sails.js#L4) which are exposed through a property on `io`.  Check that everything is loaded in the right order and that the console.log is executed after everything is loaded.

1.2 If you wanted to use sails.io directly with ngSails, you should be able to call io.sails.connect(url, config) with your url and config and it will return a socket.

2. ngSails tells sails.io to [not connect automatically](https://github.com/janpantel/angular-sails/blob/master/src/service/angular-sails.js#L4).  ngSails [starts the connection](https://github.com/janpantel/angular-sails/blob/master/src/service/angular-sails.js#L80) when it is invoked.  Its always done this, but now it checks if a `io.sails.connect` function is available and uses it over the normal `io.connect`

**Comment by prisonier** [comment]
2. Nice, i was scared it could be a 1. related
1. Well, this is my code : 


``` html
<script src="/js/base_dependencies/sails.io.js"></script>
<script src="/js/base_dependencies/angular.js"></script>
<script src="/js/base_dependencies/jquery.min.js"></script>
<script src="/js/other_dependencies/angular-cookie.min.js"></script>
<script src="/js/other_dependencies/angular-route.min.js"></script>
<script src="/js/other_dependencies/angular-sails.js"></script>
<script src="/js/angular/app.js"></script>
<script src="/js/angular/config/cache.js"></script>
<script src="/js/angular/config/location.js"></script>
<script src="/js/angular/config/route.js"></script>
<script src="/js/angular/config/run.js"></script>
<script src="/js/angular/controller/StarCtrl.js"></script>
<script src="/js/angular/factory/StarFactory.js"></script>
```


Then in my Controller : 

```javascript
app.controller('StarCtrl', ['$scope', 'StarFactory', '$location', '$routeParams', function ($scope, StarFactory, $location, $routeParams) {

  $scope.loading = true

  StarFactory.getStarSocket($routeParams.readable_id)
    .then(function (star) {

      $scope.star = star

    }, function (msg) {

      console.log(msg)
      $location.path('/')

    }).then(function(){
      $scope.loading = false
    })

}])
```

And my factory : 

``` javascript
app.factory('StarFactory', ['$http', '$q', '$sails', function($http, $q, $sails){

  var factory = {
    star : false,


    getStarSocket : function(readable_id){
      var deferred = $q.defer()

      console.log(io)

      io.socket.get('/star/profile/'+readable_id, function(star, jwres){

        if(jwres.statusCode === 200){
          factory.star = star
          deferred.resolve(factory.star)
        }else{
          deferred.reject('error')
        }
      })

      return deferred.promise

    },
  }

  return factory
}])
```


Sorry, console.log(io) give me something, console.log(io.socket) returns undefined so i suppose evrything is not loaded ?

Console.log

``` javascript
 function lookup(uri,opts){if(typeof uri=="object"){opts=uri;uri=undefined}opts=opts||{};var parsed=url(uri);var source=parsed.source;var id=parsed.id;var io;if(opts.forceNew||opts["force new connection"]||false===opts.multiplex){debug("ignoring socket cache for %s",source);io=Manager(source,opts)}else{if(!cache[id]){debug("new io instance for %s",source);cache[id]=Manager(source,opts)}io=cache[id]}return io.socket(parsed.path)}
```

And the error
``` javascript
 TypeError: Cannot read property 'get' of undefined
    at Object.factory.getStarSocket (http://localhost:1337/js/angular/factory/StarFactory.js:32:16)
    at new <anonymous> (http://localhost:1337/js/angular/controller/StarCtrl.js:5:15)
    at Object.invoke (http://localhost:1337/js/base_dependencies/angular.js:4185:17)
    at $get.extend.instance (http://localhost:1337/js/base_dependencies/angular.js:8454:21)
    at http://localhost:1337/js/base_dependencies/angular.js:7700:13
    at forEach (http://localhost:1337/js/base_dependencies/angular.js:331:20)
    at nodeLinkFn (http://localhost:1337/js/base_dependencies/angular.js:7699:11)
    at compositeLinkFn (http://localhost:1337/js/base_dependencies/angular.js:7078:13)
    at publicLinkFn (http://localhost:1337/js/base_dependencies/angular.js:6957:30)
    at newCompile (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1532:22) <div ng-hide="loading" ng-view="" class="ng-scope">
```

**Comment by TheSharpieOne** [comment]
Can you put a gist up with the sails.io.js file you have.  With v0.11, I am not too sure what version of sails.io.js they are using.  The sails.io.js repo only has [v0.10 releases](https://github.com/balderdashy/sails.io.js/releases). Sails.io.js has a bunch of v0.11 related tags, but I would like to see the specific one you have.

This dependency on sails.io.js becoming a problem and is slated to be solved in angular-sails v2 where we remove the dependency.

**Comment by prisonier** [comment]
i generated sails.io.js with command "sails generate sails.io.js --force" as described in 0.11 migration guide. -> https://github.com/balderdashy/sails/blob/master/0.11-migration-guide.md

https://gist.github.com/prisonier/a59ea9102196abe37c74

**Comment by prisonier** [comment]
Note that i don't really care about using sails.io now ngSails is working, it is just to let you aware of this issue.

Finally the solution to make ngSails working was to update it to v 1.1.0

**Comment by TheSharpieOne** [comment]
Ok, so that is the very latest tag for sails.io.js.  What is happening is: when you use $sails, it will set `io.sails.autoConnect` to `false` sails.io will see this and remove `io.socket`.  From this point you will need to use `$sails` like this: 
$sails will determine if there was an error or not, using a similar thing to checking for 200 statusCode.
```
$sails.get('/star/profile/'+readable_id).success(function(star){
    factory.star = star;
    deferred.resolve(factory.star);
}).error(function(){
    deferred.reject('error');
});
```
Or, get all of the response back with $sails
```
$sails.get('/star/profile/'+readable_id).then(function(data, status, headers, jwr){
    factory.star = data.star;
    deferred.resolve(factory.star);
},function(data, status, headers, jwr){
    deferred.reject('error');
});
```
OR use sails.io.js directly even when $sails is loaded (not sure why you would want to do this)
```
io.socket = io.sails.connect(); // you'd have to do this at least once somewhere.
io.socket.get('/star/profile/'+readable_id, function(star, jwres){
    if(jwres.statusCode === 200){
        factory.star = star
        deferred.resolve(factory.star)
    }else{
        deferred.reject('error')
    }
});
```

**Comment by prisonier** [comment]
Ok i understand how is it working now. Many thanks !
